# version: "3.8"
# services:
#     db-dev:
#         image: postgres:latest
#         restart: always
#         env_file:
#             - .env
#         environment:
#             - POSTGRES_DB=${POSTGRESQL_DEV_DB}
#             - POSTGRES_USER=${POSTGRESQL_DEV_USER}
#             - POSTGRES_PASSWORD=${POSTGRESQL_DEV_PASSWORD}
#         ports:
#             - "5432:5432"
#         volumes:
#             - db:/var/lib/postgresql/data
# volumes:
#     db:
#         driver: local

# version: '3.8'
# services:
#     db:
#         image: postgres:16.2-bookworm
#         container_name: db
#         # env_file:
#         #     - .env
#         environment:
#             - POSTGRES_DB= ${DB_NAME}
#             - POSTGRES_USER= ${DB_USER}
#             - POSTGRES_PASSWORD= ${DB_PASSWORD}
#         ports:
#             - ${DB_PORT}:${DB_PORT}
#             - "5432:5432"
#         volumes:
#             - db_data:/var/lib/postgresql/data
#         restart: unless-stopped
#     app:
#         build:
#             context: .
#             dockerfile: Dockerfile
#             args:
#                 DATABASE_URL: ${DATABASE_URL}
#         container_name: app
#         depends_on:
#             db:
#                 condition: service_started
#         env_file:
#             - .env
#         # environment:
#         #     DATABASE_URL: ${DATABASE_URL}
#         ports:
#             - ${PORT}:${PORT}
#             - 3000:3000
#         # volumes:
#         #     - .:/app
#         restart: unless-stopped
# volumes:
#     db_data:
#         name: db_data
